apiVersion: v1
kind: ServiceAccount
metadata:
  name: runtime-builder-iam
  namespace: stage-05-runtime
  annotations:
    eks.amazonaws.com/sts-regional-endpoints: "true"
automountServiceAccountToken: false
