apiVersion: apps/v1
kind: Deployment
metadata: {name: runtime-builder, namespace: stage-04-gitops}
spec:
  replicas: 1
  selector: {matchLabels: {app: runtime-builder}}
  template:
    metadata:
      labels: {app: runtime-builder}
      annotations: {lab.vuln-mlops/stage-04-proof: "FLAG{stage_4_gitops_placeholder}"}
    spec:
      automountServiceAccountToken: false
      securityContext: {runAsNonRoot: true, runAsUser: 101, runAsGroup: 101, seccompProfile: {type: RuntimeDefault}}
      containers:
        - name: runtime-builder
          image: nginxinc/nginx-unprivileged:1.29.1-alpine@sha256:27985295bdb22a1ef8f712863210bd5877c0f3006494a593e86b3fe0fa55467e
          ports: [{name: http, containerPort: 8080}]
          env: [{name: STAGE4_MODE, value: git-controlled}]
          readinessProbe: {httpGet: {path: /, port: http}, initialDelaySeconds: 2, periodSeconds: 5}
          livenessProbe: {httpGet: {path: /, port: http}, initialDelaySeconds: 10, periodSeconds: 10}
          resources:
            requests: {cpu: 10m, memory: 32Mi}
            limits: {cpu: 100m, memory: 64Mi}
          securityContext: {allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: {drop: ["ALL"]}}
          volumeMounts: [{name: tmp, mountPath: /tmp}]
      volumes: [{name: tmp, emptyDir: {}}]
