apiVersion: v1
kind: Service
metadata:
  name: modelgate
  namespace: modelgate-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: modelgate
  ports:
    - name: http
      port: 80
      targetPort: http
