apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-04-gitops
resources:
  - namespace.yaml
  - vendor/application-crd-v3.5.3.yaml
  - vendor/appproject-crd-v3.5.3.yaml
  - vendor/applicationset-crd-v3.5.3.yaml
  - vendor/argocd-namespace-install-v3.5.3.yaml
  - git-server.yaml
  - redis-secret.yaml
  - runtime-builder-base.yaml
  - argocd-config.yaml
  - participant-status-rbac.yaml
  - admission-policy.yaml
  - network-policy.yaml
patches:
  - target: {group: rbac.authorization.k8s.io, version: v1, kind: Role, name: argocd-application-controller}
    path: controller-role-patch.yaml
  - target: {kind: Deployment, name: argocd-applicationset-controller}
    patch: |-
      - {op: replace, path: /spec/replicas, value: 0}
  - target: {kind: Deployment, name: argocd-dex-server}
    patch: |-
      - {op: replace, path: /spec/replicas, value: 0}
  - target: {kind: Deployment, name: argocd-notifications-controller}
    patch: |-
      - {op: replace, path: /spec/replicas, value: 0}
  - target: {kind: Deployment, name: argocd-server}
    patch: |-
      - {op: replace, path: /spec/replicas, value: 0}
  - target: {kind: Deployment, name: argocd-redis}
    patch: |-
      - {op: add, path: /spec/template/spec/automountServiceAccountToken, value: false}
      - {op: remove, path: /spec/template/spec/initContainers}
images:
  - name: quay.io/argoproj/argocd
    newName: quay.io/argoproj/argocd
    newTag: v3.5.3@sha256:dd3f47d5a5e4da563a7a398506e892481b358a7cec50abdf320c71aa55904bfa
  - name: public.ecr.aws/docker/library/redis
    newName: public.ecr.aws/docker/library/redis
    digest: sha256:08ad0b1d280850169a790dba1393ff7a90aef951fc19632cf4d3ce4f78e679ba
