apiVersion: v1
kind: Pod
metadata:
  name: stage-03-client
  namespace: stage-02-rbac
  labels: {lab.vuln-mlops/role: stage-03-client}
spec:
  serviceAccountName: monitoring-runner
  automountServiceAccountToken: true
  restartPolicy: Never
  securityContext: {runAsNonRoot: true, runAsUser: 65532, runAsGroup: 65532, seccompProfile: {type: RuntimeDefault}}
  containers:
    - name: client
      image: curlimages/curl:8.16.0@sha256:463eaf6072688fe96ac64fa623fe73e1dbe25d8ad6c34404a669ad3ce1f104b6
      command: ["sleep", "600"]
      securityContext: {allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: {drop: ["ALL"]}}
