apiVersion: v1
kind: Namespace
metadata:
  name: stage-03-monitoring
  labels:
    lab.vuln-mlops/stage: "03"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
